### ISSUE TITLE
Show apparatus collection progress on quota screen

### ISSUE THREAD

**Issue by SrMoroxide** [Kamppix/ApparatusRetrieval#7]
Similar to the ApparatusQuota mod (abandoned mod with sync bugs)
Show players the amount of Apparatus needed to fill the quota, so that users who share large mod packs, who don't know which mods each have, can know that they have the obligation to grab the apparatus.

**Comment by Kamppix** [comment]
Hi!

This mod is more focused on being a standalone experience completely separated from the vanilla game, and without too many other mods interfering. This means that, as the mod description says: "you have only one goal: Retrieve the apparatus." Considering this, I don't think there should ever be a scenario where players would be unaware of their task to retrieve the apparatus (especially since you can't progress in the game otherwise).

Still, your suggestion did inspire me to make the quota screen show the progress. That will be coming in the next version along with some other cool stuff, as soon as I can fix the countless bugs.
